#!/bin/sh
. /lib/functions/uci-defaults.sh

#set system
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system

#set wireless
uci set wireless.radio1.htmode='HE160'
uci set wireless.radio1.channel='auto'
uci set wireless.radio1.country='CN'
uci set wireless.radio1.cell_density='0'
uci delete wireless.default_radio0.disabled
uci delete wireless.default_radio1.disabled
uci delete wireless.radio0.disabled
uci delete wireless.radio1.disabled
uci commit wireless
wifi reload

#set network
#uci set network.lan.ipaddr="192.168.0.1"
#uci set network.globals.ula_prefix=""
#uci set network.@device[0].multicast_to_unicast='0'
#uci commit network

#set uhttpd
#uci del uhttpd.main.listen_http
#uci del uhttpd.main.listen_https
#uci add_list uhttpd.main.listen_http=[::]:1089
#uci add_list uhttpd.main.listen_http=0.0.0.0:1089
#uci add_list uhttpd.main.listen_https=[::]:1443
#uci add_list uhttpd.main.listen_https=0.0.0.0:1443
#uci set uhttpd.main.rfc1918_filter=0
#uci set uhttpd.main.cert=/etc/ssl/certs/netshi.cn.cer
#uci set uhttpd.main.key=/etc/ssl/certs/netshi.cn.key
#uci commit uhttpd



#set root passwd and rsa cert
#sed -i '/root/d' /etc/shadow
#sed -i '1i\root:$1$G.elgsxV$IBS8iGDyioldPta4rAH0h0:19065:0:99999:7:::' /etc/shadow


# set ssr
echo "config global
	option netflix_server 'nil'
	option netflix_proxy '0'
	option threads '0'
	option dports '2'
	option pdnsd_enable '1'
	option tunnel_forward '8.8.4.4:53'
	option monitor_enable '1'
	option enable_switch '1'
	option switch_time '667'
	option switch_timeout '5'
	option switch_try_count '3'
	option gfwlist_url 'https://cdn.jsdelivr.net/gh/YW5vbnltb3Vz/domain-list-community@release/gfwlist.txt'
	option chnroute_url 'https://ispip.clang.cn/all_cn.txt'
	option nfip_url 'https://cdn.jsdelivr.net/gh/QiuSimons/Netflix_IP/NF_only.txt'
	option adblock_url 'https://anti-ad.net/anti-ad-for-dnsmasq.conf'
	option global_server 'cfg064a8f'
	option run_mode 'gfw'
config server_subscribe
	option proxy '0'
	option auto_update_time '2'
	option auto_update '1'
	option filter_words ''
	option switch '1'
	list subscribe_url ''
config access_control
	option lan_ac_mode '0'
	option router_proxy '1'
	list wan_fw_ips '149.154.160.0/20'
    	list wan_fw_ips '67.198.55.0/24'
    	list wan_fw_ips '91.108.4.0/22'
    	list wan_fw_ips '91.108.56.0/22'
    	list wan_fw_ips '109.239.140.0/24'
	list Interface 'lan'
	list Interface 'wg'
config socks5_proxy
	option server 'nil'
	option local_port '1080'
config server_global
	option enable_server '0'
	" > /etc/config/shadowsocksr

#set adguardhome
echo 'bind_host: 0.0.0.0
bind_port: 3000
beta_bind_port: 0
users:
- name: root
  password: ""
auth_attempts: 5
block_auth_min: 15
http_proxy: ""
language: zh-cn
debug_pprof: false
web_session_ttl: 720
dns:
  bind_hosts:
  - 0.0.0.0
  port: 11553
  statistics_interval: 1
  querylog_enabled: false
  querylog_file_enabled: false
  querylog_interval: 6h
  querylog_size_memory: 1000
  anonymize_client_ip: false
  protection_enabled: true
  blocking_mode: default
  blocking_ipv4: ""
  blocking_ipv6: ""
  blocked_response_ttl: 60
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com
  ratelimit: 0
  ratelimit_whitelist: []
  refuse_any: false
  upstream_dns:
  - 119.29.29.29
  - 114.114.114.114
  - 223.6.6.6
  - 2400:3200::1
  - 2001:4860:4860::8888
  upstream_dns_file: ""
  bootstrap_dns:
  - 112.65.184.255
  - 210.22.84.3
  - 2408:8888:0:8888::8
  - 2408:8899:0:8899::8
  all_servers: false
  fastest_addr: false
  fastest_timeout: 1s
  allowed_clients:
  - 192.168.0.0/24
  - 127.0.0.1
  - 0.0.0.0
  - fd1b:f0df:ced7::/64
  - ::1
  disallowed_clients:
  - 125.124.239.233
  blocked_hosts:
  - version.bind
  - id.server
  - hostname.bind
  trusted_proxies:
  - 127.0.0.0/8
  - ::1/128
  cache_size: 4194304
  cache_ttl_min: 0
  cache_ttl_max: 0
  cache_optimistic: true
  bogus_nxdomain: []
  aaaa_disabled: false
  enable_dnssec: false
  edns_client_subnet: false
  max_goroutines: 300
  ipset: []
  filtering_enabled: true
  filters_update_interval: 1
  parental_enabled: false
  safesearch_enabled: true
  safebrowsing_enabled: false
  safebrowsing_cache_size: 1048576
  safesearch_cache_size: 1048576
  parental_cache_size: 1048576
  cache_time: 30
  rewrites: []
  blocked_services: []
  upstream_timeout: 10s
  local_domain_name: lan
  resolve_clients: false
  use_private_ptr_resolvers: false
  local_ptr_upstreams: []
tls:
  enabled: false
  server_name: ""
  force_https: true
  port_https: 9443
  port_dns_over_tls: 9853
  port_dns_over_quic: 9784
  port_dnscrypt: 0
  dnscrypt_config_file: ""
  allow_unencrypted_doh: false
  strict_sni_check: false
  certificate_chain: ""
  private_key: ""
  certificate_path: ""
  private_key_path: ""
filters:
- enabled: true
  url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
  name: AdGuard DNS filter
  id: 1628750870
- enabled: true
  url: https://anti-ad.net/easylist.txt
  name: anti
  id: 1628750871
- enabled: true
  url: https://neodev.team/lite_adblocker
  name: lite_adblocker
  id: 1645339240
- enabled: true
  url: https://raw.hellogithub.com/hosts
  name: github
  id: 1645339241
whitelist_filters: []
user_rules:
  - "@@||msg.qy.net^$important"
  - "@@||tyty.log-global.aliyuncs.com^$important"
  - "@@||api.share.mob.com^$important"
  - ""
dhcp:
  enabled: false
  interface_name: ""
  dhcpv4:
    gateway_ip: ""
    subnet_mask: ""
    range_start: ""
    range_end: ""
    lease_duration: 86400
    icmp_timeout_msec: 1000
    options: []
  dhcpv6:
    range_start: ""
    lease_duration: 86400
    ra_slaac_only: false
    ra_allow_slaac: false
clients: []
log_compress: false
log_localtime: false
log_max_backups: 0
log_max_size: 100
log_max_age: 3
log_file: ""
verbose: false
os:
  group: ""
  user: ""
  rlimit_nofile: 0
schema_version: 12' > /etc/adguardhome.yaml



echo "config AdGuardHome 'AdGuardHome'
	option httpport '3000'
	option configpath '/etc/adguardhome.yaml'
	option workdir '/etc/AdGuardHome'
	option logfile '/tmp/AdGuardHome.log'
	option verbose '0'
	option binpath '/usr/bin/AdGuardHome'
	option redirect 'dnsmasq-upstream'
	option waitonboot '1'
	option ucitracktest '1'
	option enabled '1'
	list old_redirect 'dnsmasq-upstream'
	list old_port '11553'
	list old_enabled '1'" > /etc/config/AdGuardHome 

#set crontab
echo "10 2 * * 6 sleep 70 && touch /etc/banner && reboot" > /etc/crontabs/root

exit 0
